import React from 'react'
import PreNavbar from './PreNavbar'
import Footer from './Footer'


const TandC = () => {
  return (
    <div>
      <PreNavbar />
    <div className = "title"> 
        <p id='align'>India's Finest Halls</p>
    </div>

    <div className="title2" >
        <h3 id = "setlogo"><img src={require('../photos/logo.png')} height={70} width={200} alt="logo" /> </h3>
    </div>

    <div className="venuecards">
    <p id="terms">TERMS & CONDITIONS</p>
    <h3 id="termimg"><img src={require('../photos/terms.jpeg')} height={400} width={500} alt="logo" /></h3>
    <p id="tc">SKI EVENTS Tech Private Limited ("SKIEVENT" or "SKI") is a event management website that provides valuable event-related information for the modern prospective thoughts. The services offered by us include the SKIEVENT websites located at skievent.com or any sub domain of skievent.com (the "SkiEventWebsite"), the Skievent event planning app, SkiEvent For Business (Vendor) app, Eventsta app and any other feature, content or applications offered from time to time by SkiEvent in connection with the SkiEvent Website whether accessed directly or through our application for mobile devices (collectively, the "SkiEvent Services"). <br></br><br></br>SkiEvent is only a platform that connects prospect event clients and vendors that the Clients are willing to associate with to undertake their services. SkiEvent is a event aggregation platform.

These Terms of Use (this "Agreement") set forth the legally binding terms for your use and are to be complied with in addition to any agreement or terms agreed upon between the Parties for the SkiEvent Services. By using the SkiEvent Services, whether as a "Visitor" (meaning you simply browse the SkiEvent website) or as a "User" (meaning you have registered with and/or submitted content to the SkiEvent website either as an individual or as a company), you agree to be bound by this Agreement and the SkiEvent Privacy Policy located at www.SkiEvent.com/privacy.<br></br><br></br> This Agreement includes your rights, obligations and restrictions regarding your use of the SkiEvent Services, please read it carefully. User (and “You”) may refer to both Customers as well as Vendors for the purpose of this Agreement. The term “Customer” shall refer to individuals or Parties undertaking SkiEvent Services through the SkiEvent platform and the term “Vendor” refers to the individual or entities listed on the WMG platform who provide services independently to the customers.
If you do not agree with the Terms of this Agreement, you should leave the SkiEvent Website and discontinue use of the SkiEvent Services immediately.<br></br><br></br> If you wish to become a User, submit content, video or images, communicate with other Users and generally make use of the SkiEvent Services, you must read this Agreement and indicate your acceptance during the content submission process. By using the SkiEvent services or by doing any of the above, you are complying with all our terms and conditions and clauses mentioned hereinafter.
SkiEvent may modify this Agreement from time to time and each modification will be effective when it is posted on the SkiEvent Website. You agree to be bound to any changes to this Agreement through your continued use of the SkiEvent Services. You will not be notified of any modifications to this Agreement so it is important that you review this Agreement regularly to ensure you are updated as to any changes.
<br></br><br></br>
You may not post, modify, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information belonging to SkiEvent or others (including without limitation Third Party Content or SkiEvent Content) without obtaining the prior written consent of the owner of such copyrighted material, trademarks, or other proprietary information.
Since SkiEvent is a content-heavy platform, owing to the content generated by SkiEvent as well as their multiple vendors and customers, SkiEvent takes copyright & Intellectual property/proprietary rights extremely seriously.
If we become aware that one of our users is a repeat copyright infringer, it is our policy to take reasonable steps within our power to terminate that user. Without limiting the foregoing, if you believe that your work has been copied and posted on the SkiEvent Services in a way that constitutes copyright infringement, please provide us with relevant proof and we'll be happy to take corrective action accordingly.<br></br><br></br>
<br></br><b>SKIEVENT has all rights reserved under its name. <br></br>We are registered as SKIEVENT and do not promote the booking of our featured halls for any illegal events or events that might produce hazardous results.<br></br><br></br><br></br>
WE URGE YOU TO THINK BEFORE YOU UPLOAD, SUBMIT OR EMBED CONTENT. THIS AGREEMENT PERMITS YOU TO UPLOAD TO , SUBMIT TO OR EMBED ON THE SkiEvent SERVICES ONLY PHOTOS OR OTHER CONTENT THAT YOU OWN THE COPYRIGHT TO OR OTHERWISE HAVE THE RIGHT TO PUBLISH. BY UPLOADING, SUBMITTING OR EMBEDDING PHOTOS OR OTHER CONTENT THAT YOU DO NOT OWN THE COPYRIGHT TO OR DO NOT OTHERWISE HAVE THE RIGHT TO PUBLISH, YOU MAY SUBJECT YOURSELF TO LEGAL LIABILITY (SEE E.G., SECTIONS 4, 5 AND 6 BELOW). IT IS YOUR RESPONSIBILITY TO ENSURE YOU HAVE ADEQUATE RIGHTS TO PUBLISH TO THE SkiEvent SERVICES ALL PHOTOS AND OTHER CONTENT YOU POST AND SkiEvent TAKES NO LIABILITY OF THE SAME WHATSOEVER.</b></p>
    



</div>



    <div className="card7">
      <br></br>
      <h3 id="follow">FOLLOW US ON / DOWNLOAD THE SKIEVENT APP</h3>
      <h3 id="im"><img src={require('../photos/followus.png')} height={245} width={190} alt="logo" /></h3>
      <p id="imm"><img src={require('../photos/downloadapp.png')} height={245} width={200} alt="logo" /></p>
    </div>
     
     <Footer />
   

    </div>
  )
}

export default TandC;